---
# yamllint disable rule:line-length
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - --autofix
      - id: detect-aws-credentials
      - id: detect-private-key
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: ad1b27d73581aa16cca06fc4a0761fc563ffe8e8 # v1.5.6
    hooks:
      - id: forbid-tabs
        exclude_types:
          - python
          - javascript
          - dtd
          - markdown
          - makefile
          - xml
        exclude: binary|\.bin$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: e72a3ca1632f0b11a07d171449fe447a7ff6795e # v0.48.0
    hooks:
      - id: markdownlint
